export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const POST_CREATE_USER_REQUEST = 'POST_CREATE_USER_REQUEST';
export const POST_CREATE_USER_SUCCESS = 'POST_CREATE_USER_SUCCESS';
export const POST_CREATE_USER_FAILED = 'POST_CREATE_USER_FAILED';