export const FETCH_ALL_TODOS_REQUEST = 'FETCH_ALL_TODOS_REQUEST';
export const FETCH_ALL_TODOS_SUCCESS = 'FETCH_ALL_TODOS_SUCCESS';
export const FETCH_ALL_TODOS_FAILED = 'FETCH_ALL_TODOS_FAILED';

export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';

export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILED = 'CREATE_TODO_FAILED';